thresholds:
  # days
  green: 60
  yellow: 180

groups:
  - name: Distro components
    repos:
    - coreos/afterburn
    - coreos/bootupd
    - coreos/console-login-helper-messages
    - coreos/coreos-installer
    - coreos/ignition
    - coreos/rpm-ostree
    - coreos/toolbox
    - coreos/zincati
    - ostreedev/ostree

  - name: Utilities
    repos:
    - coreos/butane
    - coreos/cargo-vendor-filterer

  - name: Libraries
    repos:
    - coreos/cap-std-ext
    - coreos/envsubst-rs
    - coreos/go-json
    - coreos/go-semver
    - coreos/go-systemd
    - coreos/ign-converter
    - coreos/ignition-config-rs
    - coreos/liboverdrop-rs
    - coreos/openat-ext
    - coreos/openssh-keys
    - coreos/stream-metadata-go
    - coreos/stream-metadata-rust
    - coreos/vmw_backdoor-rs
